// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:agichat/models/model_dropdown.dart' as prefix1;
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'ModelDropdown',
            r'.ModelDropdown',
            134217735,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 3, 8, 9, 10],
            const <int>[11, 12, 13, 14, 15, 4, 5, 6, 7, 8, 9],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, title, parentId, text}) => b
                  ? prefix1.ModelDropdown(
                      parentId: parentId, text: text, id: id, title: title)
                  : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'id',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'title',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.VariableMirrorImpl(
            r'parentId',
            67240965,
            0,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3, const <int>[], const []),
        r.VariableMirrorImpl(
            r'text',
            67240965,
            0,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 5),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 6),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 3, 7),
        r.MethodMirrorImpl(
            r'dropdownId',
            2097155,
            0,
            -1,
            2,
            2,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'dropdownTitle',
            2097155,
            0,
            -1,
            2,
            2,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'',
            128,
            0,
            -1,
            0,
            0,
            const <int>[],
            const <int>[0, 1, 2, 3],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 5, 5, const <int>[],
            const <int>[4], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 2, 2, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[5],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 1, 1, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 6, 6, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'id',
            134358022,
            10,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            #id),
        r.ParameterMirrorImpl(
            r'title',
            134358022,
            10,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            #title),
        r.ParameterMirrorImpl(
            r'parentId',
            67253254,
            10,
            const prefix0.JsonSerializable(),
            -1,
            3,
            3,
            const <int>[],
            const [],
            null,
            #parentId),
        r.ParameterMirrorImpl(
            r'text',
            67253254,
            10,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            #text),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            11,
            const prefix0.JsonSerializable(),
            -1,
            7,
            7,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            13,
            const prefix0.JsonSerializable(),
            -1,
            8,
            8,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.ModelDropdown,
        int,
        String,
        int,
        String,
        bool,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'id': (dynamic instance) => instance.id,
        r'title': (dynamic instance) => instance.title,
        r'parentId': (dynamic instance) => instance.parentId,
        r'text': (dynamic instance) => instance.text,
        r'dropdownId': (dynamic instance) => instance.dropdownId,
        r'dropdownTitle': (dynamic instance) => instance.dropdownTitle
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
